# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       qmlmail

# >> macros
# << macros

Summary:    Mail application for nemo
Version:    0.0.7
Release:    1
Group:      Applications/System
License:    GPLv2
URL:        https://github.com/nemomobile/qmlmail
Source0:    %{name}-%{version}.tar.bz2
Source100:  qmlmail.yaml
Requires:   qt-components-qt5
Requires:   libqmfmessageserver1-qt5
Requires:   nemo-qml-plugin-email-qt5 >= 0.0.8
Requires:   qmlsettings-account-plugin-email
Requires:   mapplauncherd-booster-qtcomponents-qt5
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5WebKit)
BuildRequires:  pkgconfig(qdeclarative5-boostable)
BuildRequires:  desktop-file-utils

%description
Mail application using Qt Quick for Nemo Mobile.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/qmlmail
%{_datadir}/applications/qmlmail.desktop
# >> files
# << files
