# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       qmlmail

# >> macros
# << macros

Summary:    Mail application for nemo
Version:    0.0.7
Release:    1
Group:      Applications/System
License:    GPLv2
URL:        https://github.com/nemomobile/qmlmail
Source0:    %{name}-%{version}.tar.bz2
Source100:  qmlmail.yaml
Requires:   qt-components >= 1.4.8
Requires:   libqmfmessageserver1
Requires:   nemo-qml-plugin-email
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtWebKit)
BuildRequires:  pkgconfig(qdeclarative-boostable)
BuildRequires:  desktop-file-utils

%description
Mail application using Qt Quick for Nemo Mobile.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/qmlmail
%{_datadir}/applications/qmlmail.desktop
# >> files
# << files
